# Generated by Django 4.2.6 on 2023-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=100000)),
                ('photo', models.ImageField(upload_to='Item')),
                ('authorName', models.CharField(max_length=100)),
                ('barcode_id', models.IntegerField(default=0)),
                ('inStock', models.IntegerField(default=0)),
                ('deliveryDuration', models.IntegerField(default=1)),
            ],
        ),
    ]
